### ISSUE TITLE
Many links not working

### ISSUE THREAD

**Issue by holmesmi** [subsurface/subsurface#1972]
### Describe the issue:

- X Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Operating system:

MacOS

### Steps to reproduce:

Attempting to download the mac version from the website, or go to the video tutorial, results in links that go nowhere.

**Comment by dirkhh** [comment]
The tutorial video is so old that I removed it. Need to fix that the links are still there (I thought I did that already. Oops)
The Mac download is more concerning. I'll look at it.
Thanks

**Comment by dirkhh** [comment]
The download links should be fixed. that was an odd error. I still need to remove the links to the tutorial video

**Comment by gerardsn** [comment]
Downloads are still not working properly.
Depending on what language the page is using, the download refer to either subsurface-divelog.org/**download**/file or subsurface-divelog.org/**downloads**/file.
Only the **downloads** one works.

e.g. when viewing the subsurface-divelog.org/download (note missing s) page in English or German, the download buttons are pointing to the correct locations while using Dutch or Italian will result in an error as it is pointing to the wrong location for the files.

**Comment by dirkhh** [comment]
I believe this has finally been fixed. Thanks for pointing out this oversight

**Comment by fmatray** [comment]
Somes links are still broken in the french version :
https://subsurface-divelog.org/fr/documentation/
