### ISSUE TITLE
[Bug]: Download failures for Garmin Descent Mk2i on MacOS

### ISSUE THREAD

**Issue by stantonc** [subsurface/subsurface#4661]
### Description

Details can be found in this thread: https://groups.google.com/g/subsurface-divelog/c/_Kg-ILO8GI8

**Steps to Reproduce:**
1.) Connect Garmin Mk2i to the laptop with a USB cable
2.) Open Subsurface
3.) Wait a moment ... the watch always needs a moment to be ready
4.) Import -> Import from dive computer
5.) Vendor: Garmin; Dive computer: Descent Mk2(i)/Mk3(i)(S)/G1/G2/X50i; Device or mount point: blank
6.) Click Download button

**Expected Behavior:** 
Subsurface imports the most recent dives from my Garmin. This behavior worked as expected up to and including Subsurface version 6.0.5365.

**Actual Behavior:**
Starting with version 6.0.5404 and including 6.0.5436, the import fails with a "Dive data import error." Dumping the log file shows:

Subsurface: v6.0.5404.0, built with libdivecomputer v0.9.0-devel-Subsurface-NG (26221352623426bbc36166c9eccde923d1879cb9)
[0.000000] INFO: Open MTP device
[0.000208] INFO: Read: size=0, data=
[0.000224] ERROR: Failed to open directory 'Garmin/Activity' or ''. [in src/garmin.c:505 (garmin_device_foreach)]

Garmin Connect connects with the watch just fine on the same Mac, and downgrading to 6.0.5365 restores the correct behavior. This appears to be a regression of some kind starting after this version.

**Platform:**
Sequoia 15.7.3 on a Macbook Pro M4

### Subsurface Version

6.0.5436

### Platform(s)

macOS

### Platform Version

15.7.3

### Divecomputer Model

Garmin Descent Mk2i

### Steps to Reproduce

1.) Connect Garmin Mk2i to the laptop with a USB cable
2.) Open Subsurface
3.) Wait a moment ... the watch always needs a moment to be ready
4.) Import -> Import from dive computer
5.) Vendor: Garmin; Dive computer: Descent Mk2(i)/Mk3(i)(S)/G1/G2/X50i; Device or mount point: <blank>
6.) Click Download button

### Logs

```shell
Subsurface: v6.0.5404.0, built with libdivecomputer v0.9.0-devel-Subsurface-NG (26221352623426bbc36166c9eccde923d1879cb9)
[0.000000] INFO: Open MTP device
[0.000208] INFO: Read: size=0, data=
[0.000224] ERROR: Failed to open directory 'Garmin/Activity' or ''. [in src/garmin.c:505 (garmin_device_foreach)]
```

**Comment by dirkhh** [comment]
Known and already reported bug. Fixed in 6.0.5494 and newer.
I generally consider it a reasonable idea to test the latest build before filing a bug report.

(also, I'm on a dive trip right now, and I downloaded from my Descent Mk2i on my Mac minutes ago...)

**Comment by stantonc** [comment]
Apologies for not thinking about checking the developer version. I didn't see an existing bug and the discussion thread hadn't been updated in a while, so I assumed it was still unreported. I verified the issue appears fixed on 6.0.5503. 

Thanks for the update and fix!

**Comment by mrchen911** [comment]
I just upgraded to 6.0.5504-CICD-release and this issue persists for me. 

Garmin Mk3i is connected via USB and can be seen in file explorer:

<img width="674" height="224" alt="Image" src="https://github.com/user-attachments/assets/4a617d8c-86a8-495f-a498-4451283e502d" />

help -> About in Subsurface

<img width="501" height="575" alt="Image" src="https://github.com/user-attachments/assets/20fc9a77-2d99-4b4e-b8bb-448e00bec52b" />

Input from dive computer, Garmin and mk3i selected. Of note, attempts to browse for a device or mount point do not show the garmin device. Following the directions in this thread, it is blank.

<img width="746" height="559" alt="Image" src="https://github.com/user-attachments/assets/b3bc0087-760d-4fd9-b872-3feb6529b36a" />

Click Download and receive the Dive data import error message box. 

<img width="750" height="564" alt="Image" src="https://github.com/user-attachments/assets/6e2ba70d-ecff-424d-8519-001c42fa7214" />

**Comment by mrchen911** [comment]
I exported the log file as well:

Subsurface: v6.0.5504.0, built with libdivecomputer v0.10.0-devel-Subsurface-NG (a81bda4fc5aeb92b2a6653060abaf6173adcc6f7)
[0.000000] INFO: Open MTP device
[0.000012] INFO: Read: size=0, data=
[0.000067] ERROR: Failed to open directory 'Garmin/Activity' or ''. [in src/garmin.c:533 (garmin_device_foreach)]

**Comment by Subsurface-divelog** [comment]
my understanding is that the Mk3i is not an MTP device and ONLY works with the "mount filesystem and import FIT files" method. I don't have access to an Mk3 (I have an Mk1 and Mk2), so I can't confirm that.

**Comment by mikeller** [comment]
> I just upgraded to 6.0.5504-CICD-release and this issue persists for me.
> 
> Garmin Mk3i is connected via USB and can be seen in file explorer:
> 
> <img alt="Image" width="674" height="224" src="https://private-user-images.githubusercontent.com/907838/529288960-4a617d8c-86a8-495f-a498-4451283e502d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjY0MzMzODQsIm5iZiI6MTc2NjQzMzA4NCwicGF0aCI6Ii85MDc4MzgvNTI5Mjg4OTYwLTRhNjE3ZDhjLTg2YTgtNDk1Zi1hNDk4LTQ0NTEyODNlNTAyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIyMlQxOTUxMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGY3NGQzOTRiODExYmRiNjc0MzA0YzVkZTJjMjc3MzU2ZjYxMTI5ZmM0MTFjMWRiZjFiZTRhM2Y4OTZlODQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sm3gkx21CAmruB_6xUUWwcCM097x5Xpxu5xUUhwaOnc">


Only seeing the device in file explorer isn't enough - you need to actually open it so you can see the files on it:

<img width="656" height="323" alt="Image" src="https://github.com/user-attachments/assets/6621cdc0-6352-4ec5-b97d-1903d2c2a6f9" />


> Input from dive computer, Garmin and mk3i selected. Of note, attempts to browse for a device or mount point do not show the garmin device. Following the directions in this thread, it is blank.
> 
> <img alt="Image" width="746" height="559" src="https://private-user-images.githubusercontent.com/907838/529289821-b3bc0087-760d-4fd9-b872-3feb6529b36a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjY0MzMzODQsIm5iZiI6MTc2NjQzMzA4NCwicGF0aCI6Ii85MDc4MzgvNTI5Mjg5ODIxLWIzYmMwMDg3LTc2MGQtNGZkOS1iODcyLTNmZWI2NTI5YjM2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIyMlQxOTUxMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YmJiNWU3M2MxMGM0ZWE2MjYwZGMzZGQyYWE5Yjg2YmFmZmI5ZjNkYTllMGFmNDBhMTA3NzlmOGFiYjI0MjFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rLB1tqu1kcgMRJdC3On6Ok11-wgiBVpX6dPtJbwpdjk">


You then need to select this device in the directory selection dialog ([...]):

<img width="630" height="266" alt="Image" src="https://github.com/user-attachments/assets/d8cda414-2005-4f18-9258-ee2fc7dcae1a" />

<img width="486" height="174" alt="Image" src="https://github.com/user-attachments/assets/8c011fa3-d1b4-46f6-a495-a6ccf93968b1" />

**Comment by mrchen911** [comment]
That's interesting, mine doesn't mount a drive letter. I tried copying the path from file explorer but it didn't work (didn't expect it to). I'll look into seeing how to map a drive letter.

**Comment by mikeller** [comment]
> That's interesting, mine doesn't mount a drive letter. I tried copying the path from file explorer but it didn't work (didn't expect it to). I'll look into seeing how to map a drive letter.

To ask the obvious: Have you tried clicking on it?
